export const ADD_NEW_DECK = 'ADD_NEW_DECK'
export const RECEIVE_DECKS = 'RECEIVE_DECKS'
export const SET_CURRENT_DECK = 'SET_CURRENT_DECK'
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'